### ISSUE TITLE
Can not start addon

### ISSUE THREAD

**Issue by blazkom** [stefangries/hassio-addons#1]
I have problem that i can not start addon. Also I do not have homegear folder inside /config folder

**Comment by hiol83** [comment]
I can't start it too.

19-12-04 02:19:37 ERROR (SyncWorker_2) [hassio.docker] Can't start addon_69c7aa1d_homegear: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyUSB0": no such file or directory")
